### ISSUE TITLE
One set of media queries could be left as the default

### ISSUE THREAD

**Issue by finnhodgkin** [FACN3/WDYNAC#32]
Because you only have two media sizes you could get rid of one of the following media queries and just have the styles applied by default.
```css
@media (max-width: 600px) {
  .menu__desktop {
    display: none;
  }
  p{
    width: 80%;
  }
}

/* desck-top */

@media (min-width: 601px) {
  .menu__mobile {
    display: none;
  }
  p{
    width: 60%;
  }
}
```

could become something like the following:

```css
.menu__mobile {
  display: none;
}
p{
  width: 60%;
}

@media (max-width: 600px) {
  .menu__desktop {
    display: none;
  }
  .menu__mobile {
    display: inline;
  }
  p{
    width: 80%;
  }
}
```
